import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import swaggerUi from 'swagger-ui-express';
import { RegisterRoutes } from './routes/routes'; // Generated by tsoa

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(helmet());

app.use((req, res, next) => {
  console.log(`[AUTH] ${req.method} ${req.originalUrl}`);
  next();
});

// Initialize routes generated by tsoa
RegisterRoutes(app);

// Serve Swagger docs
app.use('/docs', swaggerUi.serve, async (req: Request, res: Response) => {
  const swaggerDocument = require('../build/swagger.json');
  return res.send(swaggerUi.generateHTML(swaggerDocument));
});

// Error handling middleware
app.use(function errorHandler(
  err: unknown,
  req: Request,
  res: Response,
  next: NextFunction
): Response | void {
  if (err instanceof Error) {
    return res.status(500).json({
      message: 'Internal Server Error',
      details: err.message,
    });
  }
  next();
});

export { app };
